import type { Metadata } from "next";
import { Montserrat, Poiret_One } from "next/font/google";
import "./globals.css";

// Font-family for text - primary
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

// Font-family for heading - secondary
const poiretOne = Poiret_One({
  variable: "--font-poiret-one",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${poiretOne.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
